# Constants for user activity
XP_FOR_COMPLETING_MODULE = 10
XP_FOR_COMPLETING_CHALLENGE = 20
XP_FOR_COMPLETING_REVIEW = 10
QUIZ_ACCURACY_THRESHOLD = 80
GEMS_FOR_COMPLETING_DAILY_GOAL = 5
GEMS_FOR_COMPLETING_MONTHLY_GOAL = 10
GEMS_FOR_WEEKLY_COMPLETION_QUOTA = 10
# cost of hint in gems
GEMS_FOR_HINT = 5
# cost of bonus challenge in gems
GEMS_FOR_BONUS_CHALLENGE = 10
