"""Remove content_file_path from Module

Revision ID: 226fca9da8da
Revises: 
Create Date: 2024-10-18 18:55:41.069230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226fca9da8da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('content_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_file_path', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
