"""make module order optional

Revision ID: 22afd66ac32c
Revises: e58c2666eab9
Create Date: 2024-11-13 20:31:12.230953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22afd66ac32c'
down_revision = 'e58c2666eab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
