"""Add type to Badge model

Revision ID: 40759952b75f
Revises: 226fca9da8da
Create Date: 2024-11-05 15:16:45.442802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40759952b75f'
down_revision = '226fca9da8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('CONTENT', 'AWARD', name='badgetype'), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
