"""add last_leaderboard_reward_date to Users table

Revision ID: 4b77ac3913c1
Revises: 647cfc4c0735
Create Date: 2025-02-25 14:51:10.266700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b77ac3913c1'
down_revision = '647cfc4c0735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_case_outputs_test_case_id'), ['test_case_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_leaderboard_reward_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_leaderboard_reward_date')

    with op.batch_alter_table('test_case_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_outputs_test_case_id'))

    # ### end Alembic commands ###
