"""Add completed_date for user modules

Revision ID: 555d710fcdc8
Revises: 22afd66ac32c
Create Date: 2024-11-14 20:28:22.936370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555d710fcdc8'
down_revision = '22afd66ac32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.drop_column('completed_date')

    # ### end Alembic commands ###
