"""add test_case_outputs table

Revision ID: 647cfc4c0735
Revises: 65e049e2083e
Create Date: 2025-02-19 10:41:38.542606

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "647cfc4c0735"
down_revision = "65e049e2083e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_case_outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_case_id", sa.Integer(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_column("output")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("output", sa.TEXT(), nullable=False))

    op.drop_table("test_case_outputs")
    # ### end Alembic commands ###
