"""Make target_module a string

Revision ID: 65e049e2083e
Revises: 6f4e18516c76
Create Date: 2025-01-28 16:39:24.181222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e049e2083e'
down_revision = '6f4e18516c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('target_runtime',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.alter_column('submitted_runtime',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.alter_column('submitted_runtime',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('target_runtime',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
