"""Add target_runtime to Module

Revision ID: 6f4e18516c76
Revises: 2c4d0d16f601
Create Date: 2025-01-28 16:36:10.480673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4e18516c76'
down_revision = '2c4d0d16f601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_runtime', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_runtime', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.drop_column('submitted_runtime')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('target_runtime')

    # ### end Alembic commands ###
