"""Remove image src string from Badge model

Revision ID: 8fd2eb0cd2da
Revises: 40759952b75f
Create Date: 2024-11-05 15:22:47.858416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd2eb0cd2da'
down_revision = '40759952b75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_column('image_src')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_src', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
