"""Add xp tracking to User and DailyUserActivity

Revision ID: a879f8e0f9f0
Revises: 555d710fcdc8
Create Date: 2024-11-17 16:15:32.924365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a879f8e0f9f0'
down_revision = '555d710fcdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_user_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_earned', sa.Integer(), nullable=True))

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_module_type'), ['module_type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('xp')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_module_type'))

    with op.batch_alter_table('daily_user_activity', schema=None) as batch_op:
        batch_op.drop_column('xp_earned')

    # ### end Alembic commands ###
