"""Add streak_extended field to DailyUserActivity

Revision ID: e8fb7b6143f5
Revises: a879f8e0f9f0
Create Date: 2024-11-18 16:00:20.536661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb7b6143f5'
down_revision = 'a879f8e0f9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_user_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_extended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_user_activity', schema=None) as batch_op:
        batch_op.drop_column('streak_extended')

    # ### end Alembic commands ###
